/**
 * ui.js — auto-builds the whole dashboard body from an FCD/1 descriptor.
 * No board-specific code: every panel is generated by walking
 * checks[]/rails[]/graphs[]/params[]/actions[] from the descriptor JSON.
 */
import { ScrollChart } from "./chart.js";

const ACCENTS = {
  cyan: "#3fd0ff", blue: "#5b8cff", green: "#4ade80", red: "#f87171",
  yellow: "#fbbf24", magenta: "#e879f9", orange: "#fb923c", white: "#e2e8f0",
};

export function accentColor(name) {
  return ACCENTS[name] || ACCENTS.cyan;
}

function el(tag, cls, html) {
  const e = document.createElement(tag);
  if (cls) e.className = cls;
  if (html !== undefined) e.innerHTML = html;
  return e;
}

// ── header ───────────────────────────────────────────────────────────────────
export function renderHeader(profile) {
  const accent = accentColor(profile.accent);
  document.documentElement.style.setProperty("--accent", accent);
  document.getElementById("boardName").textContent = profile.name || "FLIGHT COMPUTER";
  document.getElementById("boardSub").textContent = profile.sub || "";
  document.getElementById("boardFw").textContent = profile.fw ? `fw ${profile.fw}` : "";
}

// ── preflight checks ─────────────────────────────────────────────────────────
export function buildChecks(profile) {
  const host = document.getElementById("checksPanel");
  host.innerHTML = "";
  const state = {}; // id -> {row, statusEl, status}
  if (!profile.checks.length) {
    host.appendChild(el("div", "empty-hint", "Board declared no checks[]."));
    return state;
  }
  for (const c of profile.checks) {
    const row = el("div", "check-row");
    const dot = el("span", "check-dot pending");
    const label = el("span", "check-label", c.label);
    const detail = el("span", "check-detail", "monitoring…");
    row.append(dot, label, detail);
    host.appendChild(row);
    state[c.id] = { dot, detail, status: "pending" };
  }
  return state;
}

export function setCheckStatus(state, id, status, detail) {
  const s = state[id];
  if (!s) return;
  s.status = status;
  s.dot.className = `check-dot ${status}`;
  if (detail) s.detail.textContent = detail;
}

// ── rails (voltage bars) ─────────────────────────────────────────────────────
export function buildRails(profile) {
  const host = document.getElementById("railsPanel");
  host.innerHTML = "";
  const state = {};
  if (!profile.rails.length) {
    host.appendChild(el("div", "empty-hint", "Board declared no rails[]."));
    return state;
  }
  for (const r of profile.rails) {
    const wrap = el("div", "rail");
    const top = el("div", "rail-top");
    top.append(el("span", "rail-label", r.label), el("span", "rail-value", "—"));
    const track = el("div", "rail-track");
    const fill = el("div", "rail-fill");
    track.appendChild(fill);
    const range = el("div", "rail-range", `${r.min ?? "?"} – ${r.max ?? "?"} V`);
    wrap.append(top, track, range);
    host.appendChild(wrap);
    state[r.id] = { rail: r, valueEl: top.children[1], fill };
  }
  return state;
}

export function updateRail(state, id, value) {
  const s = state[id];
  if (!s) return;
  const { rail, valueEl, fill } = s;
  valueEl.textContent = `${Number(value).toFixed(2)} V`;
  const lo = rail.min ?? 0, hi = rail.max ?? (Number(value) || 1);
  const span = Math.max(hi - lo, 0.01);
  const pct = Math.min(100, Math.max(0, ((value - lo) / span) * 100));
  fill.style.width = `${pct}%`;
  const edgeBand = span * 0.08;
  let cls = "ok";
  if (value < lo || value > hi) cls = "bad";
  else if (value < lo + edgeBand || value > hi - edgeBand) cls = "warn";
  fill.className = `rail-fill ${cls}`;
}

// ── graphs (scrolling sparklines) ───────────────────────────────────────────
export function buildGraphs(profile) {
  const host = document.getElementById("graphsPanel");
  host.innerHTML = "";
  const charts = {};
  if (!profile.graphs.length) {
    host.appendChild(el("div", "empty-hint", "Board declared no graphs[]."));
    return charts;
  }
  const accent = accentColor(profile.accent);
  for (const g of profile.graphs) {
    const card = el("div", "graph-card");
    const top = el("div", "graph-top");
    top.append(el("span", "graph-label", g.label), el("span", "graph-live", "—" + (g.unit ? ` ${g.unit}` : "")));
    const canvasWrap = el("div", "graph-canvas-wrap");
    const canvas = document.createElement("canvas");
    canvasWrap.appendChild(canvas);
    card.append(top, canvasWrap);
    host.appendChild(card);
    charts[g.id] = {
      chart: new ScrollChart(canvas, { unit: g.unit, accent }),
      liveEl: top.children[1],
      unit: g.unit,
    };
  }
  return charts;
}

export function pushGraphSample(charts, id, t, value) {
  const c = charts[id];
  if (!c) return;
  c.chart.push(t, value);
  c.liveEl.textContent = `${Number(value).toFixed(2)}${c.unit ? " " + c.unit : ""}`;
}

// ── event log ────────────────────────────────────────────────────────────────
const LOG_MAX = 400;
export function initLog() {
  const host = document.getElementById("logPanel");
  host.innerHTML = "";
  return { host, err: 0, warn: 0 };
}

export function appendLogLine(logState, level, msg, tLabel) {
  const host = logState.host;
  const row = el("div", `log-row lvl-${level.toLowerCase()}`);
  row.append(
    el("span", "log-time", tLabel || ""),
    el("span", "log-level", level),
    el("span", "log-msg", msg)
  );
  host.appendChild(row);
  while (host.children.length > LOG_MAX) host.removeChild(host.firstChild);
  host.scrollTop = host.scrollHeight;
  if (level === "ERR") logState.err++;
  if (level === "WARN") logState.warn++;
  document.getElementById("logErrCount").textContent = logState.err;
  document.getElementById("logWarnCount").textContent = logState.warn;
}

// ── params (editable settings) ───────────────────────────────────────────────
export function buildParams(profile, onSet) {
  const host = document.getElementById("paramsPanel");
  host.innerHTML = "";
  const nonPyro = profile.params.filter((p) => p.id !== "fire_mode");
  if (!nonPyro.length) {
    host.appendChild(el("div", "empty-hint", "Board declared no params[]."));
    return;
  }
  for (const p of nonPyro) {
    const row = el("div", "param-row");
    const label = el("div", "param-label", p.label || p.id);
    if (p.unit) label.innerHTML += ` <span class="dim">(${p.unit})</span>`;
    let input;
    if (p.type === "enum" && p.values) {
      input = document.createElement("select");
      for (const v of p.values) {
        const opt = el("option", "", v);
        opt.value = v;
        if (v === p.value) opt.selected = true;
        input.appendChild(opt);
      }
    } else if (p.type === "bool") {
      input = document.createElement("select");
      for (const v of ["off", "on"]) {
        const opt = el("option", "", v);
        opt.value = v;
        input.appendChild(opt);
      }
      input.value = p.value ? "on" : "off";
    } else {
      input = document.createElement("input");
      input.type = "text";
      input.value = p.value ?? "";
      if (p.min != null || p.max != null) {
        input.placeholder = `${p.min ?? ""}..${p.max ?? ""}`;
      }
    }
    input.className = "param-input";
    const btn = el("button", "btn btn-small", "set");
    const status = el("span", "param-status");
    btn.onclick = async () => {
      const val = input.tagName === "SELECT" ? input.value : input.value.trim();
      status.textContent = "…";
      const reply = await onSet(p.id, val);
      status.textContent = reply;
      status.className = `param-status ${reply.startsWith("ERR") ? "bad" : "ok"}`;
    };
    row.append(label, input, btn, status);
    host.appendChild(row);
  }
}

// ── actions (buttons, args, confirm/danger) ─────────────────────────────────
function openConfirmModal({ title, body, token, danger, onConfirm }) {
  const overlay = el("div", "modal-overlay");
  const modal = el("div", danger ? "modal modal-danger" : "modal");
  const h = el("div", "modal-title", title);
  const b = el("div", "modal-body", body || "");
  modal.append(h, b);
  let input = null;
  if (token) {
    input = document.createElement("input");
    input.className = "modal-input";
    input.placeholder = `type ${token} to confirm`;
    input.autocomplete = "off";
    modal.appendChild(input);
  }
  const row = el("div", "modal-actions");
  const cancel = el("button", "btn", "Cancel");
  const confirm = el("button", danger ? "btn btn-danger" : "btn btn-primary", danger ? `Confirm ${token || ""}` : "Confirm");
  row.append(cancel, confirm);
  modal.appendChild(row);
  overlay.appendChild(modal);
  document.body.appendChild(overlay);
  if (input) {
    input.focus();
    const check = () => { confirm.disabled = input.value.trim() !== token; };
    input.addEventListener("input", check);
    check();
  }
  const close = () => overlay.remove();
  cancel.onclick = close;
  confirm.onclick = () => { if (!confirm.disabled) { close(); onConfirm(); } };
  overlay.addEventListener("click", (e) => { if (e.target === overlay) close(); });
}

export function buildActions(profile, onInvoke) {
  const host = document.getElementById("actionsPanel");
  host.innerHTML = "";
  // pyro-specific actions get their own panel (pyro.js); skip the well-known
  // ids here so they aren't rendered twice.
  const PYRO_IDS = new Set(["arm", "disarm", "prime", "fire", "deploy_ready", "session_key", "safe"]);
  const rest = profile.actions.filter((a) => !PYRO_IDS.has(a.id) || !profile.hasPyro);
  if (!rest.length) {
    host.appendChild(el("div", "empty-hint", "No other actions."));
    return;
  }
  for (const a of rest) {
    const btn = el("button", `btn ${a.danger ? "btn-danger" : ""}`, a.label);
    btn.onclick = async () => {
      const args = {};
      for (const argSpec of a.args || []) {
        const hint = argSpec.values ? argSpec.values.join("/") : `${argSpec.min ?? ""}..${argSpec.max ?? ""}`;
        const v = prompt(`${argSpec.label || argSpec.id} (${hint}):`);
        if (v === null) return;
        args[argSpec.id] = v;
      }
      const fire = () => onInvoke(a.id, args, btn);
      if (a.confirm) {
        openConfirmModal({
          title: a.label,
          body: a.danger ? "This is a danger action. It still passes through the board's own interlocks." : "",
          token: a.confirm,
          danger: a.danger,
          onConfirm: fire,
        });
      } else {
        fire();
      }
    };
    host.appendChild(btn);
  }
}

export { openConfirmModal, el };
